### ISSUE TITLE
Consider layering the SDK to decrease size

### ISSUE THREAD

**Issue by stianlagstad** [cognitedata/cognite-sdk-python#257]
Pandas and numpy are heavy dependencies. We should consider splitting the SDK into a very thin layer that communicates with the API, and a thicker layer which includes utilities such as pandas.

**Comment by dragly** [comment]
I would be careful to introduce layering because of the additional implementation and maintenance cost it typically introduces. It is easy to end up with twice as many places in the code that needs to be implemented and maintained for every action, attribute, endpoint, etc. However, if the thin layer is auto-generated based on the API spec and the thick layer is the only thing that we need to maintain manually, layering could be a good idea.

Alternatively, we could use lazy loading of heavy modules. That is, to move the pandas import inside functions like `to_pandas` or `from_pandas`. It is also worth noting that Apache Arrow solves this by wrapping Pandas in a thin compatibility layer: https://github.com/apache/arrow/blob/master/python/pyarrow/table.pxi

That being said, I think this should be decided based on the audience of the SDK. If we are mainly targeting data scientists for the Python SDK, then I think depending on Pandas and NumPy is perfectly fine. On the other hand, if we expect many users to write lightweight Python apps that are feeding or fetching data on low-end devices, a thinner API may be usable. But in the lightweight case, calling the API directly might be just as easy?

**Comment by stianlagstad** [comment]
Good input, @dragly! If lazy loading works as it sounds, that sounds like a good option.

> But in the lightweight case, calling the API directly might be just as easy?
I disagree with this. I've used the Python SDK on several occasions (without ever needing pandas, numpy, etc.) and it has saved me a lot of time.

**Comment by dragly** [comment]
Interesting, @stianlagstad! Do you have some examples of use-cases where you used the Python SDK without Pandas and NumPy? Just good to know in case other users are using the SDK for the same purposes :slightly_smiling_face:

**Comment by stianlagstad** [comment]
Sure!

In extractors:
1. witsml-extractor: https://github.com/cognitedata/witsml-extractor
2. opc-ua-extractor: https://github.com/cognitedata/opcua-extractor
3. db-extractor: https://github.com/cognitedata/db-extractor

In other tools:
1. data replicator: https://github.com/cognitedata/data-replicator (replicate data from one CDP project to another, I think)
2. raw input generator: https://github.com/cognitedata/raw-input-generator. A simple tools that SA's have used.
3. Johans cdp tools: https://github.com/cognitedata/johan-cdp-cli (just an example - lots of people have smaller tool/demo repos which just require simple sdk functionality)

We have four pages of python repositories in our cognitedata org (search: https://github.com/cognitedata?utf8=%E2%9C%93&q=&type=&language=python), and lots of these use the Python SDK. Lots of those again only require the simple SDK - not the heavy stuff such as pandas and numpy.

**Comment by erlendvollset** [comment]
We will most likely go for an approach where we do lazy loading of heavier dependencies.

Then we will create two distributions of the sdk, one library `cognite-sdk` will specify all dependencies required for additional functionality, and another `cognite-sdk-core` (or something like that) which only specifies `requests` and a few other helper libraries.
