### ISSUE TITLE
Review sequences client before unmarking as experimental

### ISSUE THREAD

**Issue by erlendvollset** [cognitedata/cognite-sdk-python#453]
Once Sequences API has been released in v1 we should do a review of the current client implementation and settle on an interface. Thinking in particular about the following:

- implementing a custom data class for sequence data. 
- .insert_dataframe() method
- .rows() method on the Sequence object.

**Comment by sanderland** [comment]
- one thing that keeps catching me off-guard is that create takes a column object with camelCase names, and returns a column list of dicts where [c.id for c in seq.columns] doesn't work (since it's c['id']), which clashes with seq.id being fine.
- delete_range is not supported in the api, but could be in the sdk

**Comment by sanderland** [comment]
All of the above are done in 1.0.4, but will leave this open for further comments
